# You will probably want to configure these values to whatever you expect to hit Plex-Board as. e.g. http://plexdashboard.whatever.com/
# If you're running behind a reverse-proxy, e.g. http://bob.com/plex-board/, then the relative_root field should be configured.
# In the above example the relative_root would be set to: '/plex-board'
# Please note that the format above does matter, prefix with the '/' and don't use a trailing slash.
# You shouldn't need to include any url paths in the web_host and asset_host fields.
# 0.0.0.0 might not work on windows, you can change this to 127.0.0.1 or whatever IP address you want Plex-Board to listen on

use_reverse_proxy: false
relative_root:
web_host: 127.0.0.1
#On unix systems this port will be ignored when use_reverse_proxy is set to true. This is because puma will run on a unix socket instead.
port: 3000

# Windows users will need to change both the web_host and asset_host from 0.0.0.0 to a valid IP address on the host.
# If you're just testing it locally then http://127.0.0.1:3000 should work for both values.