# The settings in this file will change how the Rails app behaves. Most users shouldn't have to change these settings.


# This should be set to whatever IP address your host will respond to requests from.
# Most *nix users can leave this at 0.0.0.0, but if you have issues then you'll need to bind to a specific interface.
# run: ifconfig to find out what IP addresses your system has configured.
# Also 0.0.0.0 may be invalid on some systems like Windows and some Raspberry Pi distros (or when IPv6 is enabled sometimes)
# so if you have issues then set it to something else
# Example: 192.168.0.1
# Default: 0.0.0.0
web_host: 0.0.0.0


# This is the port that Rails will bind to. If you want to run the app on default http port 80 then you'll probably need
# to run it as root.
# Example: 80
# Default: 3000
port: 3000


# Most users won't run the app behind a reverse proxy, if you don't know that that is then leave this alone.
# Example: true
# Default: false
use_reverse_proxy: false


# relative_root should be set to the path that the app is under. So "/plexdashboard" (omit the trailing "/") would
# mount the app under (using 127.0.0.1 as an example web_host) http://127.0.0.1/plexdashboard
# If you change relative_root you will need to regenerate your assets by running serverSetup.sh
# Example: /plexdashboard
# Default:
relative_root:


